#!/bin/bash

# Ensure the script is given an argument
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <directory_name>"
    exit 1
fi

DIRECTORY=$1
RUBY_VERSION=3.1.2
HTMX_VERSION=1.9.6
HTMX_CDN_URL=https://unpkg.com/htmx.org

# Create the directory if it doesn't exist
mkdir -p "$DIRECTORY"

# Navigate into the directory
cd "$DIRECTORY"

# Set the ruby version
cat <<EOL > .ruby_version
$RUBY_VERSION
EOL

# Create the default directories
mkdir -p css public/css views

# Copy HTMX to the public directory
curl -L -o './public/htmx-'$HTMX_VERSION'.js' $HTMX_CDN_URL'@'$HTMX_VERSION

# Starter gems into the Gemfile
cat <<EOL > Gemfile
# frozen_string_literal: true

source "https://rubygems.org"

gem "sinatra"
gem "puma"
EOL

# Install gems
bundle install

# Create and write to tailwind.config.js
cat <<EOL > tailwind.config.js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './views/index.erb',
  ],
}
EOL

# Create the base css file for Tailwind
cat <<EOL > css/main.css
@import 'tailwindcss/base';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';
EOL

# Create and write to the config.ru file
cat <<EOL > config.ru
require './app'
run Sinatra::Application
EOL

# Create and write to the app.rb file
cat <<EOL > app.rb
require 'sinatra'
require 'securerandom'

before do
  @random = SecureRandom::uuid
end

get '/' do
  erb :index
end
EOL

# Create and write to the index.erb file
cat <<EOL > views/index.erb
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>SINATRA + HTMX</title>

  <link rel="stylesheet" href="/css/main.css?v=<%= @random %>">
  <script src="/htmx-1.9.6.js"></script>

</head>
<body>

  <header class="bg-slate-200 mb-10"><h1 class="text-lg p-6">Hello from views/index.erb</h1></header>

  <p class="p-10">
    This page is served from the default get / in Sinatra.  HTMX is installed and CSS is generated by Tailwind.  Enjoy dev-ing...
  </p>
</body>
</html>
EOL

# Create and write to the Procfile
cat <<EOL > Procfile
sinatra: rackup
tailwind: npx tailwindcss -i ./css/main.css -o ./public/css/main.css --watch
EOL

# Create and write to the Readme.md
cat <<EOL > Readme.md
# Write a Readme About This App

... so that folks know what's up
EOL

# Initialize git
git init

echo "Setup complete!"
